name: Pipeline

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      # Could be moved onto ubuntu's virtual environment?
      - name: Install Latest Docker and Lando
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
          wget https://files.devwithlando.io/lando-stable.deb
          sudo dpkg -i lando-stable.deb

      - name: Cache images
        id: cache-images
        uses: actions/cache@v2
        with:
          path: |
            /tmp/images.tar
          key: test-docker-cache

      - name: Load images
        if: steps.cache-images.outputs.cache-hit == 'true'
        run: docker load -i /tmp/images.tar

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start lando
        run: |
          lando start
          lando info
          sleep 10
          curl http://admin.sol.lndo.site/

      - name: Save images
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: |
          docker save $(docker images -q) -o /tmp/images.tar